### ISSUE TITLE
[Bug]: Pbm d'installation sur windows 

### ISSUE THREAD

**Issue by jbaubourg** [cnumr/ecoindex_scrap_python#85]
### What happened?

Après avoir installé python, pip et ecoindex-cli sur mon poste, au lancement de la commande :

`ecoindex-cli --help        `

J'ai l'erreur suivante :
```
> C:\Users\jean-baptsite>ecoindex-cli --help
> Traceback (most recent call last):
>   File "<frozen runpy>", line 198, in run_module_as_main
>   File "<frozen runpy>", line 88, in run_code
>   File "C:\Users\jean-baptsite\AppData\Roaming\Python\Python311\Scripts\ecoindex-cli.exe__main.py", line 4, in <module>
>   File "C:\Users\jean-baptsite\AppData\Roaming\Python\Python311\site-packages\ecoindex_cli\cli\app.py", line 22, in <module>
>     from ecoindex_cli.cli.helper import run_page_analysis
>   File "C:\Users\jean-baptsite\AppData\Roaming\Python\Python311\site-packages\ecoindex_cli\cli\helper.py", line 4, in <module>
>     from ecoindex_scraper.scrap import EcoindexScraper
>   File "C:\Users\jean-baptsite\AppData\Roaming\Python\Python311\site-packages\ecoindex_scraper_init_.py", line 1, in <module>
>     from .scrap import EcoindexScraper
>   File "C:\Users\jean-baptsite\AppData\Roaming\Python\Python311\site-packages\ecoindex_scraper\scrap.py", line 15, in <module>
>     from ecoindex_scraper.utils import convert_screenshot_to_webp, set_screenshot_rights
>   File "C:\Users\jean-baptsite\AppData\Roaming\Python\Python311\site-packages\ecoindex_scraper\utils.py", line 1, in <module>
>     from os import chown, unlink
> ImportError: cannot import name 'chown' from 'os' (C:\Users\jean-baptsite\AppData\Local\Programs\Python\Python311\Lib\os.py)

J'ai testé avec les version 3.7, 3.10 et 3.11 de python

### Version

^3.6

### What OS do you use?

Windows

### urls

_No response_

### Relevant log output

_No response_

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vvatelot** [comment]
Problème provient de https://github.com/cnumr/ecoindex_scrap_python/blob/59feb4bd464032bd49ffb62df5e95f84a05013f4/ecoindex_scraper/utils.py#L1 ... Pour Windows la fonction `chown` n'est pas disponible...
